[package]
name = "spl-zk-token-proof-program"
description = "Solana Program Library ZkToken Proof Program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.1.0"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
getrandom = { version = "0.1", features = ["dummy"] }
num-derive = "0.3"
num-traits = "0.2"
solana-sdk = "=1.9.1"
solana-program-runtime = "=1.9.1"
spl-zk-token-sdk = { path = "../sdk" }
